spring.application.name=xml_task

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/xml_task_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=none